### ISSUE TITLE
Can you share the beautiful es-stats UI code?

### ISSUE THREAD

**Issue by HatBoy** [jamiealquiza/es-stats#9]
Hi, I follow you README installed es-stats，But I can not show the beautiful es-stats UI, I find your code can not have the UI code, Can you share the beautiful es-stats UI code? Thank you very much!

**Comment by jamiealquiza** [comment]
Hi!

The screenshots in the README are using an older version of Grafana (template link here: https://gist.github.com/jamiealquiza/298575115337fdf03ca5) on top of regular old graphite. Let me know if you could use any further input!
